### ISSUE TITLE
SPI Operation

### ISSUE THREAD

**Issue by ahmetakman** [digidotcom/xbee_ansic_library#35]
Hi guys,
I am trying to use the XBee Pro S2c module with its SPI bus using Arduino IDE . Is there any useful resource or reference code ( might be C C++ it is okay) for this operation other than the datasheet? (which I think is quite poor in terms of SPI documentation)

**Comment by tomlogic** [comment]
There are some host libraries in other languages (Java, Python), but I'm not aware of any of those libraries including a SPI implementation.  Maybe @mikewadsten knows about some SPI-related Python code that Digi has made (or would make) available to customers?

**Comment by mikewadsten** [comment]
Driving SPI from a host device, especially if you're targeting a PC, is _very_ dependent on using some kind of chipset to implement the SPI hardware interface and move data between the PC and the SPI slave. In other words, there is no off-the-shelf Python (or Java) code for that.

@ahmetakman Since you say you're trying to use the Arduino IDE, you'll want to look for sample code for using SPI on an Arduino device as a starting point.

**Comment by tomlogic** [comment]
Since the XBee's SPI interface is rarely used, the documentation isn't as detailed as you might want if implementing it from scratch.  You could also try asking on [Digi's Forum](https://www.digi.com/support/forum/rf-solutions-and-xbee/miscellaneous-hardware-software) for XBee Hardware questions.
